mrousavy/nitro

packages/template/android/src/main/cpp/cpp-adapter.cpp
Think this might have been missed in the template. Still trying to get this up and running locally
Edit: Looking at the CMake file, i am seeing the Hybrid test object, but no `JHybridKotlinTestObjectSpec`. Guessing that will be part of the autogenerated spec. Removed the HybridImageFactory though as that looks like it comes straight from the sample proj
=> fix: template cpp-adapter.cpp for Android

packages/nitrogen/src/syntax/createType.ts, packages/nitrogen/src/syntax/types/EnumType.ts, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridKotlinTestObjectSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridKotlinTestObjectSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridKotlinTestObjectSpec.kt, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Bridge.hpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridKotlinTestObjectSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridKotlinTestObjectSpec.hpp, packages/react-native-nitro-image/src/specs/TestObject.nitro.ts
Fixes enum parsing by properly detecting the non-nullable type in unions.
This change now allows these APIs to work:
```ts
(event?: Type | TypeB)
(event: Type | TypeB)
```
Previously that broke.
- Fixes https://github.com/mrousavy/nitro/issues/125
- Fixes https://github.com/mrousavy/nitro/pull/116
=> fix: Fix optional enums in Nitrogen

example/ios/NitroExample.xcodeproj/xcshareddata/xcschemes/NitroExample.xcscheme, example/src/screens/HybridObjectTestsScreen.tsx, packages/nitrogen/src/autolinking/android/createHybridObjectInitializer.ts, packages/nitrogen/src/syntax/kotlin/KotlinHybridObjectRegistration.ts, packages/react-native-nitro-image/nitrogen/generated/android/NitroImageOnLoad.cpp, packages/react-native-nitro-image/nitrogen/generated/android/NitroImageOnLoad.hpp, packages/react-native-nitro-modules/android/src/main/cpp/platform/NitroLogger.cpp, packages/react-native-nitro-modules/android/src/main/cpp/registry/JHybridObjectRegistry.cpp, packages/react-native-nitro-modules/cpp/core/HybridFunction.hpp, packages/react-native-nitro-modules/cpp/core/HybridObject.cpp, packages/react-native-nitro-modules/cpp/jsi/JSICache.cpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+ArrayBuffer.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+HybridObject.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIHelpers.hpp, packages/react-native-nitro-modules/cpp/platform/NitroLogger.hpp, packages/react-native-nitro-modules/cpp/prototype/HybridObjectPrototype.cpp, packages/react-native-nitro-modules/cpp/registry/HybridObjectRegistry.cpp, packages/react-native-nitro-modules/cpp/threading/Dispatcher.cpp, packages/react-native-nitro-modules/cpp/turbomodule/NativeNitroModules.cpp, packages/react-native-nitro-modules/cpp/utils/NitroDefines.hpp, packages/react-native-nitro-modules/cpp/utils/OwningLock.hpp, packages/react-native-nitro-modules/cpp/utils/TypeInfo.hpp, packages/react-native-nitro-modules/ios/core/PromiseHolder.hpp, packages/react-native-nitro-modules/ios/platform/NitroLogger.mm, packages/react-native-nitro-modules/src/NativeNitroModules.ts, packages/react-native-nitro-modules/src/NitroModules.ts
Properly uses `NITRO_DEBUG` on DEBUG/!NDEBUG builds, and release code otherwise.
=> fix: Fix `NITRO_DEBUG` debug/release preprocessor directive

packages/nitrogen/src/createPlatformSpec.ts, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Umbrella.hpp
Also throw HybridObject declarations themself into the "known types" list. That way they will be forward declared in the generated Swift headers.
- Fixes https://github.com/mrousavy/nitro/issues/133
=> fix: Forward declare HybridObjects as well in Swift headers

example/ios/Podfile.lock, example/src/getTests.ts, packages/nitrogen/src/syntax/createType.ts, packages/nitrogen/src/syntax/swift/SwiftCxxBridgedType.ts, packages/react-native-nitro-image/android/src/main/java/com/margelo/nitro/image/HybridTestObjectKotlin.kt, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.cpp, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.hpp, packages/react-native-nitro-image/ios/HybridTestObjectSwift.swift, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridTestObjectSwiftKotlinSpec.kt, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Bridge.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/c++/HybridTestObjectSwiftKotlinSpecSwift.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectSwiftKotlinSpec.hpp, packages/react-native-nitro-image/src/specs/TestObject.nitro.ts, packages/react-native-nitro-modules/cpp/registry/HybridObjectRegistry.cpp, packages/react-native-nitro-modules/package.json, packages/react-native-nitro-modules/src/NativeNitroModules.ts, packages/react-native-nitro-modules/src/NativeNitroModules.web.ts, packages/react-native-nitro-modules/src/NitroModules.ts, packages/react-native-nitro-modules/src/NitroModulesTurboModule.ts, packages/react-native-nitro-modules/src/NitroModulesTurboModule.web.ts
When using a single string literal in Nitrogen, it must throw again because it is simply ambiguous between a string and an enum. We don't know what it is, so we need to tell the user to be more explicit.
Also fixes:
- Optionals in Swift can be passed through as is if possible - no optional lambda try/unwrapping
- Disable codegen for Android (it failed because I don't use it)
=> fix: Make string literals throw again, and test optional enums

packages/template/android/src/main/java/com/margelo/nitro/<<androidNamespace>>/<<androidCxxLibName>>Package.java
The `<<androidCxxLibName>>Package.java` has the `image` component package at the very top but instead should be the placeholder.
Also we can add loading the c++ library with the placeholder
=> fix: fix android placeholders

docs/docs/nitrogen.md
The nitrogen page is a step by step guide on running Nitro Codegen but following as it is now leads user to errors.
When defining the Spec, HybridObject requires a generic parameter or else the user would get:
```
❌  Failed to generate spec for RNFilePicker! Error: RNFilePicker does not properly extend HybridObject<T> - HybridObject does not have a single generic type argument for platform spec languages.
❌  No specs found in RNFilePicker.nitro.ts!
```
So this pr adds the generic type for guide completeness and exports the Spec since it is used in step 6 which I also made obvious in that step that this is the spec defined in .nitro.ts file.
Also the classes are missing the memorySize and hybridContext(for ios) for completeness. I copy pasted them, only to get a cryptic error in the …
=> fix: pass in generic types and export Specs

docs/docs/worklets.md, docs/sidebars.ts, example/ios/Podfile.lock, packages/react-native-nitro-modules/cpp/core/BoxedHybridObject.cpp, packages/react-native-nitro-modules/cpp/core/BoxedHybridObject.hpp, packages/react-native-nitro-modules/cpp/turbomodule/NativeNitroModules.cpp, packages/react-native-nitro-modules/src/NitroModules.ts, packages/react-native-nitro-modules/src/NitroModulesTurboModule.ts
While Nitro is runtime-agnostic and all `HybridObject`s can be used from a any Runtime, some threading/worklet libraries (like [react-native-worklets-core](https://github.com/margelo/react-native-worklets-core)) do not yet support copying over `HybridObject`s as they use newer JSI APIs like `jsi::NativeState`.
While those APIs are not yet available in react-native-worklets-core, you can still use every Nitro Hybrid Object in a separate Runtime/Worklet context by just boxing it yourself:
```ts
const something = NitroModules.createHybridObject<Something>('Something')
const boxed = NitroModules.box(something)
const context = Worklets.createContext('DummyContext')
context.runAsync(() => {
'worklet'
const unboxed = boxed.unbox()
console.log(unboxed.name) // --> "Something"
})
```
The …
=> feat: Add `NitroModules.box(...)` to support using Nitro Modules from any Runtime/Worklets context

packages/react-native-nitro-modules/cpp/turbomodule/NativeNitroModules.cpp, packages/react-native-nitro-modules/cpp/turbomodule/NativeNitroModules.hpp, packages/react-native-nitro-modules/src/NitroModulesTurboModule.ts
Parameter was unused anyways, so remove it.
Hybrid Objects that can be default-constructed using `createHybridObject(..)` should not take any arguments anyways, as this just overly complicates things (how do we parse the args? Do we convert them to Swift/Kotlin types? How do we length-check them? It needs to be compile-time, etc), as well as potentially uses unsafe typings (we are not in a Nitro context yet so we cannot use the JSIConverter template stuff).
If you need arguments here, create a default-constructible "factory" HybridObject first, then create your other HybridObjects from that factory with some helper methods - those are fast, type-safe, and compile-time generated.
=> fix: Remove unused `args` parameter in `createHybridObject(..)`

packages/react-native-nitro-modules/cpp/core/HybridFunction.hpp
When you accidentally destructure the HybridObject in JS, the NativeState gets lost and it cannot properly resolve the prototype anymore (by design):
```ts
const math = NitroModules.createHybridObject<Math>('Math')
const { add } = math
// ^ destructured! `this` is not bound to `math` anymore on `add`
```
This PR now provides a more helpful error message - the error thrown when trying to call `add` without a properly bound `this` now like this:
```diff
- Cannot call Math.add(...) - `this` is not bound! Suggestions:
- - Did you accidentally destructure the `HybridObject`? (`const { add } = ...`)
- - Did you call `dispose()` on the `HybridObject` before?
- - Did you accidentally call `add` on the prototype directly?
```
=> fix: Provide helpful error message if `this` is not bound

packages/nitrogen/src/syntax/swift/SwiftHybridObject.ts, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridBaseSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridChildSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageFactorySpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-modules/ios/core/HybridObjectSpec.swift
Per ["Swift Optimization Tips: Mark protocols that are only satisfied by classes as class-protocols"](https://github.com/swiftlang/swift/blob/main/docs/OptimizationTips.rst#advice-mark-protocols-that-are-only-satisfied-by-classes-as-class-protocols), marking `protocol`s as `AnyObject` could increase performance since we know that HybridObjects are never structs anyways.
=> perf: Mark all `protocol`s as `AnyObject`, since they're always classes

docs/src/pages/markdown-page.md, packages/react-native-nitro-modules/cpp/threading/CallInvokerDispatcher.hpp
Guards `CallInvokerDispatcher` only if <ReactCommon/CallInvoker.h> is available
=> fix: Make Nitro core compile on non-react-native environments

example/ios/Podfile.lock, packages/nitrogen/src/syntax/kotlin/FbjniHybridObject.ts, packages/nitrogen/src/syntax/kotlin/KotlinCxxBridgedType.ts, packages/nitrogen/src/syntax/kotlin/KotlinHybridObject.ts, packages/nitrogen/src/syntax/swift/SwiftCxxBridgedType.ts, packages/nitrogen/src/syntax/swift/SwiftCxxTypeHelper.ts, packages/nitrogen/src/syntax/swift/SwiftHybridObjectBridge.ts, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridBaseSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridChildSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridImageFactorySpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridImageSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridImageSpec.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridTestObjectSwiftKotlinSpec.kt, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Bridge.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/c++/HybridImageSpecSwift.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/c++/HybridTestObjectSwiftKotlinSpecSwift.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/swift/Car.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridBaseSpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridChildSpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageFactorySpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageSpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpecCxx.swift
Changes nitrogen to prefix all variables it allocates with a double underscore (`__`) to prevent accidental name-clashes.
=> fix: Prefix all variable names with `__`

packages/nitrogen/src/syntax/Method.ts, packages/nitrogen/src/syntax/Parameter.ts, packages/nitrogen/src/syntax/Property.ts, packages/nitrogen/src/syntax/createType.ts, packages/nitrogen/src/syntax/types/EnumType.ts, packages/nitrogen/src/syntax/types/HybridObjectType.ts, packages/nitrogen/src/syntax/types/StructType.ts
Checks if parameter names start with two underscores (`__`), and if structs are empty.
=> fix: Add more guards to nitrogen

packages/nitrogen/src/syntax/swift/SwiftHybridObjectBridge.ts, packages/nitrogen/src/syntax/types/HybridObjectType.ts, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridBaseSpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridChildSpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageFactorySpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageFactorySpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageSpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpecCxx.swift
Replaces
```swift
var something: Something
```
with
```swift
var something: any Something
```
if `Something` is a protocol
=> fix: Use `any` for protocol conformance in Swift

packages/nitrogen/src/createPlatformSpec.ts
This is different from methods. It's an actual property.
=> fix: Allow functions as properties again

example/src/getTests.ts, packages/nitrogen/src/syntax/swift/SwiftCxxTypeHelper.ts, packages/react-native-nitro-image/android/src/main/java/com/margelo/nitro/image/HybridTestObjectKotlin.kt, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.cpp, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.hpp, packages/react-native-nitro-image/ios/HybridTestObjectSwift.swift, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridTestObjectSwiftKotlinSpec.kt, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Bridge.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/c++/HybridTestObjectSwiftKotlinSpecSwift.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectSwiftKotlinSpec.hpp, packages/react-native-nitro-image/src/specs/TestObject.nitro.ts
Before, `create_std__optional_Whatever__(...)` did not use the SwiftCxxBridgedType at all. Now it does.
Added a use-case / test-case for this in `getTests()` as well: `optionalArray?: string[]`
=> fix: Also run bridge conversion in `std::optional` type helper

packages/nitrogen/src/autolinking/ios/createSwiftCxxBridge.ts, packages/nitrogen/src/syntax/swift/SwiftCxxTypeHelper.ts, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Bridge.hpp, packages/react-native-nitro-modules/cpp/utils/NitroDefines.hpp
Adds `_Nonnull` (or `NONNULL`, which is just an alias) to all `void*` types
=> fix: Add `_Nonnull` modifier to `void*` types for Swift

packages/nitrogen/src/autolinking/ios/createPodspecRubyExtension.ts, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage+autolinking.rb
Properly deals with non-Arrays in the generated `.podspec` extension (e.g. if `source_files` is a simple string)
- Fixes https://github.com/mrousavy/nitro/issues/233
=> fix: Properly deal with non-arrays in `podspec`

example/android/app/build.gradle
This PR addresses the build failure occurring during the creation of the release bundle for Android. The error was caused by the inability to determine the Hermes location.
=> Fix Hermes location detection for Android example app

packages/nitrogen/src/syntax/createType.ts, packages/nitrogen/src/syntax/getInterfaceProperties.ts, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.cpp, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.hpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.hpp, packages/react-native-nitro-image/src/specs/TestObject.nitro.ts
In addition to `interface T { ... }`, nitrogen can now also detect `type T = { ... }` types, which are the same thing on the native side (= `struct`s).
- Closes #222
=> feat: Allow `type T = {...}` definition for structs

example/src/getTests.ts, packages/nitrogen/src/syntax/kotlin/KotlinCxxBridgedType.ts, packages/react-native-nitro-image/android/src/main/java/com/margelo/nitro/image/HybridTestObjectKotlin.kt, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.cpp, packages/react-native-nitro-image/ios/HybridTestObjectSwift.swift, packages/react-native-nitro-image/nitrogen/generated/android/c++/JCar.hpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/Car.kt, packages/react-native-nitro-image/nitrogen/generated/ios/swift/Car.swift, packages/react-native-nitro-image/nitrogen/generated/shared/c++/Car.hpp, packages/react-native-nitro-image/src/specs/TestObject.nitro.ts
Booleans in JNI are actually chars. (jboolean).
So we need to cast them to bools instead.
Fixes https://github.com/mrousavy/nitro/issues/259#issuecomment-2441263658
=> fix: Fix jboolean parse in Structs

packages/nitrogen/src/autolinking/android/createCMakeExtension.ts, packages/react-native-nitro-image/nitrogen/generated/android/NitroImage+autolinking.cmake, packages/react-native-nitro-modules/android/CMakeLists.txt
react-native 0.76 merged most of their C++ shared libraries into one larger one; the `ReactAndroid::reactnative` umbrella prefab.
This unfortunately breaks all RN libs that contain C++ code, which Nitro does. So we have to add a special `if` to support this new change now and link the libs different on RN 0.75 than on RN 0.76.
- Fixes https://github.com/mrousavy/nitro/issues/262
=> feat: Add RN 0.76 support

packages/nitrogen/src/syntax/kotlin/KotlinCxxBridgedType.ts, packages/react-native-nitro-image/nitrogen/generated/android/c++/JCar.hpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/Car.kt, packages/react-native-nitro-image/nitrogen/generated/ios/swift/Car.swift, packages/react-native-nitro-image/nitrogen/generated/shared/c++/Car.hpp, packages/react-native-nitro-image/src/specs/TestObject.nitro.ts
Fixes an error where structs that contain optional bools where not properly converted from Java to C++.
```ts
interface SomeStruct {
someBool?: boolean
}
```
The reason this failed is because a Java boolean is not the same as a C++ boolean in JNI. It is an `unsigned char`, whereas a C++ boolean is a `bool`.
This cannot be implicitly converted, so we have to wrap booleans with `static_cast<bool>(value)` in order for it to work. This is what this PR now does.
And it adds the code to the example so it doesn't break in the future anymore.
- Fixes https://github.com/mrousavy/nitro/issues/259
=> fix: Fix optional bools in JNI structs

packages/react-native-nitro-image/android/build.gradle, packages/react-native-nitro-modules/android/build.gradle, packages/template/android/build.gradle
Excludes libraries that are pre-packaged by react-native.
Nitro (and nitro modules) depend on `libreactnative.so`, which is shipped by react-native - so it is a **local prefab**. 
Android thinks it needs to package all dependencies into a lib, but this is not true because RN is a peer dependency and is shared - locally. So we exclude it from Nitro's build.gradle.
- Fixes https://github.com/mrousavy/nitro/issues/269
=> fix: Exclude pre-packaged RN libs

packages/nitrogen/src/syntax/kotlin/FbjniHybridObject.ts, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridBaseSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridChildSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridImageFactorySpec.hpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridImageSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.hpp, packages/react-native-nitro-modules/android/src/main/cpp/core/ByteBufferArrayBuffer.hpp, packages/react-native-nitro-modules/android/src/main/cpp/core/JPromise.hpp
Fixes an issue where the destructor of a C++ JNI object could potentially be called from a Thread that isn't attached to the JNI environment (like a JS garbage collector thread)
- Fixes https://github.com/callstackincubator/react-native-fast-ws/issues/15
cc @grabbou
=> fix: Fix JNI destructor being potentially called from a wrong Thread

packages/nitrogen/src/config/NitroUserConfig.ts
That's `core`, `NitroModules`, and `nitro`
=> fix: Throw if a reserved keyword is used in nitrogen

packages/nitrogen/src/syntax/kotlin/KotlinFunction.ts, packages/nitrogen/src/syntax/kotlin/KotlinStruct.ts, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/Car.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/Func_void.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/Func_void_std__optional_double_.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/Func_void_std__string.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/Func_void_std__vector_Powertrain_.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/ImageSize.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/Person.kt
When using stuff from Nitro Core like `ArrayBuffer` in a Kotlin struct or function, the import was missing. This PR fixes that.
Also fixes nitro-codegen not locally rebuilding when running the `specs` command
=> fix: Import Nitro core in Kotlin struct and function

packages/template/package.json
Currently the package.json doesn't include the nitrogen folder which is needed to execute the autolinking
=> Fix built package autolinking

docs/docs/comparison.md, docs/docs/entry-point.md, docs/docs/view-components.md, docs/docs/what-is-nitro.md, docs/src/components/HomepageFeatures/index.tsx, packages/nitrogen/README.md
This PR removes small `ontop` typo found in multiple places
=> chore: remove `ontop` typo in docs

packages/nitrogen/src/syntax/kotlin/KotlinHybridObjectRegistration.ts, packages/react-native-nitro-image/nitrogen/generated/android/NitroImageOnLoad.cpp, packages/react-native-nitro-modules/android/src/main/cpp/registry/DefaultConstructableObject.hpp
Explicitly catches `ClassNotFoundException` and `NoSuchMethodError` errors, which happen when the class or constructor cannot be found by JNI.
These errors can occur when the user puts the class in the wrong namespace, forgets to implement a default-constructor, or when it gets stripped by ProGuard in release builds. In those cases, Nitro will throw with a nicer error message for the user.
=> feat: Explicitly catch `ClassNotFound` and `NoSuchMethod` errors

packages/react-native-nitro-modules/NitroModules.podspec, packages/react-native-nitro-modules/package.json
Adds support for visionOS
I have successfully run my nitro library (react-native-video v7) on visionOS by only changing podspec of `react-native-nitro-modules`! 
- Added `visionos` to platforms
- Added `visionOS` keyword to package.json
=> feat: Add visionOS support

example/src/Testers.ts, example/src/utils.ts, packages/react-native-nitro-modules/cpp/entrypoint/HybridNitroModulesProxy.cpp, packages/react-native-nitro-modules/cpp/entrypoint/HybridNitroModulesProxy.hpp, packages/react-native-nitro-modules/src/NitroModulesProxy.ts
Adds a new API to `NitroModules`: `NitroModules.hasNativeState(value)`.
With this API, we guard the `toString()` call of a HybridObject in release builds because we relied on an error being thrown, which turns into an assert (crash) in release. 
To avoid relying on an error being thrown, we instead now somewhat safely check if we can stringify an object by checking if it has `toString()` or inherits from it - and then we check if it has NativeState. It is a fair assumption that `toString()` from prototype only works if we have NativeState, at least in the Nitro world.
- Fixes https://github.com/mrousavy/nitro/issues/314
=> fix: Perform safer checks for `toContain(..)` in example, and add `NitroModules.hasNativeState(value)`

.github/workflows/build-android-release.yml
Creates a GitHub action/workflow that runs everytime a GitHub release is created.
When this happens, it will build the Nitro Example Android app in release mode and upload the .apk to the GitHub release artefacts.
That way, users can test it instantly.
=> chore: Create action that builds Android app on a GitHub release

example/src/getTests.ts, packages/nitrogen/src/syntax/swift/SwiftCxxBridgedType.ts, packages/react-native-nitro-image/android/src/main/java/com/margelo/nitro/image/HybridTestObjectKotlin.kt, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.cpp, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.hpp, packages/react-native-nitro-image/ios/HybridTestObjectSwift.swift, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridTestObjectSwiftKotlinSpec.kt, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Bridge.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/c++/HybridTestObjectSwiftKotlinSpecSwift.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectSwiftKotlinSpec.hpp, packages/react-native-nitro-image/src/specs/TestObject.nitro.ts
Adds a test that has this function signature:
```ts
func(): Promise<ArrayBuffer>
```
Apparently this broke before on iOS.
- Fixes https://github.com/mrousavy/nitro/issues/329
=> fix: Fix `Promise<ArrayBuffer>` return type generated wrong in Swift

example/src/getTests.ts, packages/react-native-nitro-image/android/src/main/java/com/margelo/nitro/image/HybridTestObjectKotlin.kt, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.cpp, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.hpp, packages/react-native-nitro-image/ios/HybridTestObjectSwift.swift, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridTestObjectSwiftKotlinSpec.kt, packages/react-native-nitro-image/nitrogen/generated/ios/c++/HybridTestObjectSwiftKotlinSpecSwift.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpecCxx.swift, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectSwiftKotlinSpec.hpp, packages/react-native-nitro-image/src/specs/TestObject.nitro.ts, packages/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/Promise.kt
Previously, `Promise` caught only `Error` on Kotlin. If you throw something else (e.g. `Exception`), this would've not been caught. So now instead we catch the highest level throwable, which is `Throwable` itself.
This catches every exception or runtime error and also carries enough string information with it to be represented as a JS error.
=> fix: Make `Promise` catch any `Throwable` instead of `Error` subclass

example/src/getTests.ts
On Android, when there are two promises, second promise will wait for the first one to resolve. 
In this example, the resolution should be:
- Promise.all(foo(), bar()) called, both functions are running
- foo() is pending
- bar() is pending
- bar gets resolved
- 2 seconds later
- foo() gets resolved
- Promise.all gets resolved
=> repro: Add test where Promise.all checks if they can run in parallel

example/src/getTests.ts, packages/react-native-nitro-modules/cpp/core/Promise.hpp
Fixes an issue where the new `Promise<T>` implementation introduced in https://github.com/mrousavy/nitro/commit/8832bc5225353e9ac0905c9a51cc57bf3dc1f076 actually caused a thread-lock since `std::future` was still used. This caused the `future` to be awaited on the JS thread instead of the background thread, making promises resolve synchronously instead of asynchronously.
The issue was caused by `std::future`/`std::shared_future`'s RAII mechanism where the destructor waits for the task to complete. Now, it is moved to a `shared_ptr` and only awaited for completion in the run function.
=> fix: Fix `Promise::awaitFuture` actually locking threads

packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Future.hpp, packages/react-native-nitro-modules/cpp/threading/ThreadPool.cpp
Use `JSIConverter<std::shared_ptr<Promise>>` instead.
=> chore: Add deprecation notice to `JSIConverter<std::future>`

packages/nitrogen/src/syntax/kotlin/KotlinCxxBridgedType.ts, packages/react-native-nitro-image/android/build.gradle, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-modules/android/build.gradle, packages/react-native-nitro-modules/android/src/main/cpp/core/JPromise.hpp, packages/react-native-nitro-modules/android/src/main/cpp/utils/JUnit.hpp, packages/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/Promise.kt, packages/template/android/build.gradle
- Uses optimization flag `-O2` in release builds
- Uses optimization flag `-O0` in debug builds
- Fixes `Promise<void>` not resolving in Kotlin
=> perf: Only enable `-O2` in release, use `-O0` in debug

packages/nitrogen/src/syntax/kotlin/KotlinEnum.ts, packages/react-native-nitro-image/nitrogen/generated/android/c++/JImageFormat.hpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JOldEnum.hpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JPixelFormat.hpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JPowertrain.hpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/ImageFormat.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/OldEnum.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/PixelFormat.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/Powertrain.kt
Generates an added `_ordinal` field for every Kotlin Enum that can be accessed through fbjni.
Previously, we accessed [`ordinal`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-enum/ordinal.html), which should've been available in every Kotlin enum, but apparently some people had issues with this (@Szymon20000 & @shovel-kun) - maybe it got compiled out? Maybe it was an older Kotlin version? Maybe it got replaced with a `ordinal()` method for some reason? I don't know. **I couldn't reproduce this bug.**
Anyways; the smartest solution I can find that didn't degrade performance (calling `ordinal()` method thru JNI is slower than accessing a field) is that we just create a shadow-property on the Kotlin enum called `_ordinal` which mirrors whatever state the parent `ordinal` **value or …
=> fix: Generate a shadow `ordinal` field for Kotlin Enums

example/src/Testers.ts, example/src/getTests.ts, packages/nitrogen/src/syntax/kotlin/KotlinCxxBridgedType.ts, packages/nitrogen/src/syntax/swift/SwiftCxxBridgedType.ts, packages/nitrogen/src/syntax/types/ErrorType.ts, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Bridge.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpecCxx.swift, packages/react-native-nitro-modules/cpp/core/HybridFunction.hpp, packages/react-native-nitro-modules/cpp/core/Promise.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Exception.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Promise.hpp, packages/react-native-nitro-modules/cpp/platform/ThreadUtils.hpp, packages/react-native-nitro-modules/cpp/templates/IsSharedPtrTo.hpp, packages/react-native-nitro-modules/cpp/utils/AssertPromiseState.hpp, packages/react-native-nitro-modules/cpp/utils/TypeInfo.hpp, packages/react-native-nitro-modules/ios/core/RuntimeError.swift, packages/react-native-nitro-modules/ios/turbomodule/NativeNitroModules+OldArch.mm, packages/react-native-nitro-modules/ios/utils/RuntimeError.hpp
Refactors the `Promise<T>` implementation to use `std::exception_ptr` instead of `std::exception` so it actually preserves the error message.
This cost me more than a full day of debugging - `std::exception` causes object slicing, because it uses the base's copy constructor. It needs to be a pointer to keep it virtual.
=> fix: Fix Promise rejections not having a message by using `std::exception_ptr` to avoid C++ object slicing

packages/react-native-nitro-modules/NitroModules.podspec, packages/react-native-nitro-modules/package.json
Adds support for macOS and tvOS support
I have successfully run my nitro library (react-native-video v7) on macOS and tvOS by only changing podspec of `react-native-nitro-modules`! 
I have set min required version for macOS & tvOS same as in `react-native-macos` 0.75 & `react-native-tvos` 0.75 (as Nitro requires react-native >= 0.75)
- Added `macos` & `tvos` to platforms
- Added `macOS` & `tvOS` keyword to package.json
=> feat: add macOS and tvOS support

packages/react-native-nitro-modules/cpp/core/HybridFunction.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Exception.hpp
Because error messages are broken in react-native core, we need to add a workaround to explicitly catch `std::runtime_error` errors in a `catch` block so we can get the error message. 
This is reported in https://github.com/mrousavy/nitro/issues/382 (and https://github.com/facebook/react-native/issues/48027).
Unfortunately we have to add this workaround on Android now, even if it is nasty and won't work for all errors.
=> fix: Add workaround for error messages on Android (`std::runtime_error`)

docs/docs/types/types.md, example/ios/Podfile.lock, packages/nitrogen/src/syntax/types/FunctionType.ts, packages/nitrogen/src/syntax/types/PromiseType.ts, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.cpp, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.hpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.hpp, packages/react-native-nitro-modules/README.md, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Function.hpp, packages/react-native-nitro-modules/cpp/templates/PromiseType.hpp, packages/react-native-nitro-modules/cpp/threading/Dispatcher.hpp
A callback that returns a value can now be awaited using the `Promise<T>` class from Nitro.
This means it now also works on Swift and Kotlin!!!
=> feat: Use `std::shared_ptr<Promise<T>>` instead of `std::future<T>` for callbacks that return a value

packages/nitrogen/src/syntax/swift/SwiftCxxBridgedType.ts, packages/nitrogen/src/syntax/swift/SwiftHybridObject.ts, packages/react-native-nitro-image/ios/HybridBase.swift, packages/react-native-nitro-image/ios/HybridChild.swift, packages/react-native-nitro-image/ios/HybridImage.swift, packages/react-native-nitro-image/ios/HybridImageFactory.swift, packages/react-native-nitro-image/ios/HybridTestObjectSwift.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridBaseSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridChildSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageFactorySpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpecCxx.swift
In Swift Hybrid Objects we previously always required the user to fill in `hybridContext` and `memorySize` because Swift protocols don't allow default values, and there's no abstract class in Swift.
I found a solution with a `typealias` tho, and now we can pre-fill `hybridContext` and `memorySize`!
For library users, this now means you can remove those fields from your Swift class;
```diff
class HybridMath: HybridMathSpec {
-  var hybridContext: margelo.nitro.HybridContext = .init()
-  var memorySize: Int { return getSizeOf(self) }  
var pi: Double { return 3.1415 } 
}
```
If you have a custom type that is heavy on memory, it is still recommended to **override** `memorySize`;
```swift
class HybridImage: HybridImageSpec {
override var memorySize: Int { return nativeImage.height * …
```
=> feat: Remove `hybridContext` and `memorySize` from Swift HybridObjects (make them optional)

.github/ISSUE_TEMPLATE/BUG_REPORT.yml, docs/docs/hybrid-objects.md, docs/docs/nitrogen.md, docs/docs/using-nitro-in-your-app.md, docs/docs/view-components.md
=> docs: Update docs to no longer use `hybridContext`

example/src/Testers.ts, packages/nitrogen/src/syntax/c++/CppHybridObject.ts, packages/nitrogen/src/syntax/createType.ts, packages/nitrogen/src/syntax/swift/SwiftCxxBridgedType.ts, packages/nitrogen/src/syntax/swift/SwiftCxxTypeHelper.ts, packages/nitrogen/src/syntax/swift/SwiftHybridObject.ts, packages/nitrogen/src/syntax/swift/SwiftHybridObjectBridge.ts, packages/nitrogen/src/syntax/swift/SwiftHybridObjectRegistration.ts, packages/nitrogen/src/syntax/types/HybridObjectType.ts, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Bridge.cpp, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Bridge.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImageAutolinking.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridBaseSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridBaseSpec_cxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridChildSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridChildSpec_cxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageFactorySpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageFactorySpec_cxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageSpec_cxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec_cxx.swift
Consider the following code:
```ts
interface Base ... {}
interface Child extends Base ... {}
interface SomeHybrid extends HybridObject<{ ios: 'swift' }> {
createChild(): Base
}
```
Previously this did **NOT** work and the returned object would have the `Base` prototype and only methods from `Base`, even if it is a `Child` on the Swift side.
Now it finally works - because if you create a `Child` it will always be a `Child`, even if the type is erased to `Base`. You can confirm this by console.logging `.__type` - previously it was `Base`, now it's `Child`.
1. Instead of statically calling `bridge.create_std__shared_ptr_margelo__nitro__image__HybridBaseSpec_(__swiftPart.toUnsafe())`, we now call `bridge.create_std__shared_ptr_margelo__nitro__image__HybridBaseSpec_(self.toUnsafe())` inside of …
=> feat: Implement proper type-erasure inheritance in Swift

docs/docs/hybrid-objects.md, docs/docs/performance-tips.md, packages/nitrogen/src/syntax/swift/SwiftHybridObject.ts, packages/nitrogen/src/syntax/swift/SwiftHybridObjectBridge.ts, packages/react-native-nitro-image/ios/HybridImage.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridBaseSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridBaseSpec_cxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridChildSpec_cxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageFactorySpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageFactorySpec_cxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageSpec_cxx.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec_cxx.swift, packages/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/HybridObject.kt, packages/react-native-nitro-modules/ios/core/HybridObjectSpec.swift, packages/react-native-nitro-modules/ios/utils/MemoryHelper.swift
The `getSizeOf(self)` function is now default-calculated, so the user doesn't have to calculate that. There's no point in calculating that, I don't know why I added that in the beginning tbh.
Replace:
```diff
class MyHybrid: MyHybridSpec {
public override var memorySize: Int {
-    return getSizeOf(self)
+    return 0
}
}
```
..or better yet;
```diff
class MyHybrid: MyHybridSpec {
-  public override var memorySize: Int {
-    return getSizeOf(self)
-    return 0
-  }
}
```
..if you just return `0` anyways. `0` is already the default.
But if you calculate size;
```swift
class MyHybrid: MyHybridSpec {
public override var memorySize: Int {
return myImage.height * myImage.bytesPerRow
}
}
```
No need for `getSizeOf(self)` anymore. **It is deprecated and will be removed in a future Nitro …
=> feat: Default-calculate `getSizeOf(...)` so the user doesn't have to

packages/nitrogen/src/syntax/swift/SwiftCxxTypeHelper.ts, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Bridge.hpp, packages/react-native-nitro-modules/cpp/core/AnyMap.hpp, packages/react-native-nitro-modules/cpp/core/Promise.hpp, packages/react-native-nitro-modules/cpp/utils/NitroDefines.hpp, packages/react-native-nitro-modules/ios/core/ArrayBufferHolder.hpp, packages/react-native-nitro-modules/ios/core/ArrayBufferHolder.swift
This PR avoids copying a few C++ types when using them in Swift, effectively speeding up the codebase by a few factors depending on how heavy the types were to copy. 🔥 
Swift imports all C++ types as value types, so every time you get, use, or pass a C++ type around in Swift, **it will make a copy.**
Not only is this slow, but sometimes it isn't even expected and might destroy internal state if the C++ class has unsafe pointers inside that are not ref-counted! ⚠️ ❌ 
`std::shared_ptr<T>` is one of these cases - if you use `shared_ptr.pointee`, it will actually return the pointer this shared_ptr wraps **by value** - so **it will copy** `T`!! ❌ 
```swift
func someSwiftFunc(shared: std.shared_ptr<T>) {
shared.pointee.doFirst()
shared.pointee.doSecond()
shared.pointee.doThird()
// 3x copy, 3x …
```
=> perf: Mark all types that are used only in `std::shared_ptr<T>` as `SWIFT_NONCOPYABLE`

packages/nitrogen/src/syntax/c++/CppEnum.ts, packages/nitrogen/src/syntax/kotlin/KotlinCxxBridgedType.ts, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/OldEnum.hpp, packages/react-native-nitro-modules/android/src/main/cpp/core/JArrayBuffer.hpp, packages/react-native-nitro-modules/android/src/main/cpp/registry/JHybridObjectRegistry.cpp, packages/react-native-nitro-modules/android/src/main/cpp/utils/JNISharedPtr.hpp, packages/react-native-nitro-modules/cpp/core/BoxedHybridObject.cpp, packages/react-native-nitro-modules/cpp/core/HybridObject.cpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Function.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Promise.hpp, packages/react-native-nitro-modules/cpp/prototype/HybridObjectPrototype.hpp, packages/react-native-nitro-modules/ios/core/RuntimeError.swift, packages/react-native-nitro-modules/ios/utils/RuntimeError.hpp
fixes a lot of warnings in the compiler output
=> chore: Remove unused arg names

packages/react-native-nitro-image/ios/HybridTestObjectSwift.swift, packages/react-native-nitro-modules/android/src/main/cpp/core/JPromise.hpp, packages/react-native-nitro-modules/cpp/core/Promise.hpp, packages/react-native-nitro-modules/cpp/threading/Dispatcher.cpp, packages/react-native-nitro-modules/ios/core/Promise.swift
If a Promise gets destroyed without ever being resolved or rejected, it goes stale.
This PR fixes this and rejects a Promise with a timeout error if it gets destructed and is still pending
=> fix: Reject Promise with timeout if it gets destroyed

packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Function.hpp
No reason for a lock here since the assumption is that we are already on the JS Thread (otherwise calling it wouldn't be safe anyways), and we have `OwningReference` - so a _strong_ one.
It can never be deleted here by the GC, so no reason to hold an `OwningLock`.
=> perf: Make JS callbacks lock-free

example/src/getTests.ts
We create a Promise on JS side, await it on native and rethrow the error on native
=> test: Add test that rejects a Promise on JS side and rethrows on native

.github/workflows/run-nitrogen.yml, package.json, packages/nitrogen/src/autolinking/android/createCMakeExtension.ts, packages/nitrogen/src/nitrogen.ts, packages/nitrogen/src/utils.ts, packages/react-native-nitro-modules/package.json
Fixes Windows support for Android codegen
=> fix: Use UNIX paths for CMake file, even on Windows (`\` -> `/`)

packages/nitrogen/src/autolinking/android/createCMakeExtension.ts
Apparently we sometimes have duplicates: https://github.com/jobpaardekooper/react-native-localize-date/blob/64226aa98a4bc5d6a1c04c28569133df48b20f0c/nitrogen/generated/android/NitroLocalizeDate%2Bautolinking.cmake#L24-L35
=> fix: Filter out duplicates for CMake extension

packages/nitrogen/src/syntax/createType.ts
When doing this:
```ts
import { SomeType } from '@src/SomeType'
```
Nitrogen might not know where to import `SomeType` from because `@src` is a path alias created from the user's `tsconfig.json`.
Nitrogen does not use the user's `tsconfig.json` though, so it has to be imported like this instead:
```ts
import { SomeType } from '../SomeType'
```
This will work.
This PR now throws a better error message in these situations:
```diff
- The TypeScript type "SomeType" cannot be represented in C++!
+ The TypeScript type "SomeType" cannot be resolved - is it imported properly? Make sure to import it properly using fully specified relative or absolute imports, no aliases.
```
- Closes #457
=> feat: Throw a better error message when using wrong imports

packages/react-native-nitro-modules/android/src/main/cpp/registry/JHybridObjectRegistry.hpp, packages/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/HybridObjectInitializer.java, packages/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/HybridObjectRegistry.java
HybridObjects should be registered from C++ instead.
=> fix: Mark Java `HybridObjectRegistry` as deprecated

docs/docs/nitrogen.md, docs/docs/types/types.md, packages/nitrogen/src/syntax/swift/SwiftHybridObject.ts, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridBaseSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageFactorySpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridImageSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-modules/README.md, packages/react-native-nitro-modules/ios/core/HybridObject.swift
Renames the `HybridObjectSpec` protocol to `HybridObject` for consistency.
=> fix: Rename `HybridObjectSpec` -> `HybridObject` protocol

packages/react-native-nitro-modules/cpp/core/HybridFunction.hpp, packages/react-native-nitro-modules/cpp/core/Promise.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Exception.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+HostObject.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+HybridObject.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Tuple.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Variant.hpp, packages/react-native-nitro-modules/cpp/prototype/HybridObjectPrototype.cpp, packages/react-native-nitro-modules/cpp/utils/AssertPromiseState.hpp, packages/react-native-nitro-modules/cpp/utils/NitroTypeInfo.hpp, packages/react-native-nitro-modules/ios/core/HybridContext.hpp, packages/react-native-nitro-modules/ios/utils/RuntimeError.hpp
TypeInfo.hpp collided with Boost's typeinfo.hpp
=> fix: Rename `TypeInfo.hpp` to `NitroTypeInfo.hpp`

example/ios/NitroExample.xcodeproj/project.pbxproj, example/ios/Podfile.lock, packages/react-native-nitro-modules/android/src/main/cpp/platform/ThreadUtils.cpp, packages/react-native-nitro-modules/cpp/jsi/JSIHelpers.hpp, packages/react-native-nitro-modules/cpp/registry/HybridObjectRegistry.cpp, packages/react-native-nitro-modules/cpp/registry/HybridObjectRegistry.hpp
If a HybridObject cannot be found, the error message now includes all other Hybrid Object names that were registered. Maybe the user made a typo.
=> fix: Log all hybrid object names as joined string to help user

example/src/getTests.ts, packages/react-native-nitro-modules/cpp/core/HybridObject.cpp, packages/react-native-nitro-modules/cpp/entrypoint/HybridNitroModulesProxy.cpp, packages/react-native-nitro-modules/cpp/entrypoint/HybridNitroModulesProxy.hpp, packages/react-native-nitro-modules/src/NitroModulesProxy.ts
This internally updates the memory-size each time a HybridObject gets passed goes from native to JS (because it calls `HybridObject::toObject(...)`, which now does that).
Also, a new API is added: `NitroModules.updateMemorySize(hybridObject)` which is doing exactly that.
=> feat: Update `memorySize` when a HybridObject makes a round-trip

packages/react-native-nitro-modules/cpp/utils/BorrowingReference+Owning.hpp, packages/react-native-nitro-modules/cpp/utils/BorrowingReference.hpp, packages/react-native-nitro-modules/cpp/utils/OwningLock.hpp, packages/react-native-nitro-modules/cpp/utils/OwningReference.hpp, packages/react-native-nitro-modules/cpp/utils/ReferenceState.hpp
This should speed up allocations of new `OwningReference`/`BorrowingReference` types!
- Instead of 4x `new T*`, we now only allocate a single state block: `new ReferenceState` - which is a struct.
- This PR also removes all mutex locking operations of `OwningReference` and `BorrowingReference`! 🥳 Only `OwningLock` and `destroy()` need to lock the mutex :)
=> perf: Make `OwningReference`/`BorrowingReference` only allocate memory block once and remove locking

packages/react-native-nitro-modules/cpp/utils/NitroDefines.hpp
In Nitro 0.22 we included `cxxreact` just to find the React Native version. 
This import broke in RN 78 because we didn't depend on `cxxreact`. So this PR removes that again, since it's gonna become unnecessary anyways in the future as the user is responsible for ensuring RN version compatibility.
=> fix: Fix `cxxreact` module import

packages/nitrogen/src/createGitAttributes.ts, packages/nitrogen/src/nitrogen.ts
When I run nitrogen, it creates a `.gitattributes` file. On the next run, it removes it again.
This PR fixes that.
=> fix: Append `.gitattributes` file as well

packages/nitrogen/src/createGitAttributes.ts, packages/nitrogen/src/getFiles.ts, packages/nitrogen/src/nitrogen.ts
Apparently sometimes `f.path` can be `undefined`, e.g. for a `.gitattributes` file - as reported by @thecynicalpaul in https://github.com/mrousavy/nitro/issues/528.
I couldn't reproduce the issue, but this PR fixes this.
=> fix: Fix `f.path` sometimes being undefined

packages/nitrogen/src/syntax/Method.ts, packages/nitrogen/src/syntax/kotlin/KotlinHybridObject.ts, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridBaseSpec.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridChildSpec.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridImageFactorySpec.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridImageSpec.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridTestObjectSwiftKotlinSpec.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridTestViewSpec.kt, packages/react-native-nitro-modules/cpp/core/Promise.hpp
For all Kotlin methods we now also define a `@JvmName` annotation to make sure Kotlin doesn't mangle it.
I don't know if it does, but maybe Kotlin mangles private function names in the JVM space.
Might fix https://github.com/mrousavy/nitro/issues/531
=> fix: Generate `@JvmName` prop for Kotlin methods

packages/react-native-nitro-modules/cpp/registry/HybridObjectRegistry.cpp
`getAllHybridObjectNames()` might return an empty array but we're trying to access the first element without checking the size.
=> fix: crash when no modules are registered

packages/react-native-nitro-modules/cpp/core/HybridFunction.hpp
Because of that RN bug where `std::exception` subclasses are not catchable by a `std::exception` catch block, we have to have an additional `std::runtime_error` catch block. Theoretically we also need a `jni::JniException` catch block, and any kind of other error that can be thrown, but for now this is okay.
This is a warning in clang, so we ignore the warning until it is fixed in react-native.
=> chore: Disable `-Wexceptions` warning on Android specific `catch` block

packages/nitrogen/src/views/CppHybridViewComponent.ts, packages/react-native-nitro-image/nitrogen/generated/shared/c++/views/HybridTestViewComponent.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/views/HybridTestViewComponent.hpp, packages/react-native-nitro-modules/src/views/getHostComponent.ts
it's disabled by RN right now anyways, but just in case.
=> feat: Add extra path for `cloneProps` to make sure we dont ever use folly

example/src/screens/ViewScreen.tsx, packages/react-native-nitro-image/android/src/main/java/com/margelo/nitro/image/HybridTestObjectKotlin.kt, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.cpp, packages/react-native-nitro-image/cpp/HybridTestObjectCpp.hpp, packages/react-native-nitro-image/ios/HybridTestObjectSwift.swift, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridTestObjectSwiftKotlinSpec.kt, packages/react-native-nitro-image/nitrogen/generated/ios/NitroImage-Swift-Cxx-Bridge.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/c++/HybridTestObjectSwiftKotlinSpecSwift.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec_cxx.swift, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectCppSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestObjectSwiftKotlinSpec.hpp, packages/react-native-nitro-image/src/specs/TestObject.nitro.ts
In this example, we test the case where we can pass a `HybridView` (reference) to a normal `HybridObject`.
This is pretty powerful, because as you can see it doesn't matter whether the `HybridObject` is implemented in C++, Swift or Kotlin - we can always pass a reference to the View to it.
The View can even be downcast to the actual class in Swift or Kotlin, and in C++ you can access all exported JS methods.
Examples:
https://github.com/mrousavy/nitro/blob/86b7b49f27073af3e68c428d01e1360e9eddaab4/packages/react-native-nitro-image/android/src/main/java/com/margelo/nitro/image/HybridTestObjectKotlin.kt#L310-L313
https://github.com/mrousavy/nitro/blob/86b7b49f27073af3e68c428d01e1360e9eddaab4/packages/react-native-nitro-image/ios/HybridTestObjectSwift.swift#L317-L320 …
=> feat: Add example to pass a HybridView to a normal HybridObject

packages/nitrogen/src/createPlatformSpec.ts, packages/nitrogen/src/getPlatformSpecs.ts, packages/react-native-nitro-modules/src/views/HybridView.ts, packages/react-native-nitro-modules/src/views/getHostComponent.ts
Now the `ref` object in `hybridRef` is typed properly.
=> fix: HybridView is now a union type..

docs/docs/view-components.md
I was playing a little bit with new `HybridView` feature, but if I follow the tutorial and use the current example code, I'll get this error when i run `bun nitro-codegen`:
```bash
❌  Failed to generate spec for CameraView! Error: Props cannot be null! CameraView<...> (HybridView) requires type arguments.
❌  No specs found in Camera.nitro.ts!
```
This PR just updated the example code to extends correct types to avoid this kind of error
=> docs: :memo: update view components examples to avoid codegen error

docs/docs/view-components.md
Stumbled across a small typo (`isBlue` instead of `enableFlash` in the Swift example) in the documentation while I was checking out Nitro Views (great work btw). Confused me for a second, so fixed it. :)
=> docs: fix typo in nitro views documentation

docs/docs/view-components.md
This PR corrects a typo in the lifecycle method names beforeUpdate and afterUpdate for both Swift and Kotlin.
Renamed `onBeforeUpdate` → `beforeUpdate`
Renamed `onAfterUpdate` → `afterUpdate`
=> docs: fix typo in lifecycle method names

packages/react-native-nitro-modules/cpp/core/Promise.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Exception.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Promise.hpp, packages/react-native-nitro-modules/cpp/utils/BorrowingReference.hpp, packages/react-native-nitro-modules/cpp/utils/WeakReference.hpp, packages/react-native-nitro-modules/ios/turbomodule/NativeNitroModules+NewArch.mm, packages/react-native-nitro-modules/ios/utils/RuntimeError.hpp
Logs the actual type of `BorrowingReference<T>`, `WeakReference<T>` and other generic `T` types instead of keeping it generic. 
Helps debug these issues: https://github.com/mrousavy/nitro/issues/565
=> fix: Log proper generic `T` types when throwing exceptions

packages/react-native-nitro-modules/cpp/core/ArrayBuffer.cpp, packages/react-native-nitro-modules/cpp/core/ArrayBuffer.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+ArrayBuffer.hpp, packages/react-native-nitro-modules/cpp/prototype/HybridObjectPrototype.cpp, packages/react-native-nitro-modules/cpp/views/CachedProp.hpp
There is a rare case in which a `nullptr` `BorrowingReference<T>` could actually be accessed from a `jsi::Runtime`.
This PR fixes the issue
- fixes https://github.com/mrousavy/nitro/issues/565
=> fix: Fix a case where a `nullptr` `BorrowingReference<T>` could be accessed

docs/docs/nitrogen.md
Hi, it seems like that [from version 0.6.0](https://github.com/mrousavy/nitro/issues/93) it's required to call `HybridObject` constructor since it's virtual, this PR add this suggestions inside the docs.
Maybe would be also helpful to specify it somewhere in the doc so we can avoid this error at runtime, if someone have any suggestion I can it ofc:
```
Cannot default-construct HybridObject!
```
=> docs: :memo: add explicitly call to HybridObject constructor

packages/react-native-nitro-modules/cpp/core/HybridFunction.hpp
Fixes a small warning. No idea why `jsi::Function::createFromHostFunction` takes a `unsigned int`, but `jsi::HostFunctionType` receives a `size_t`... 🤔
=> fix: Fix implicit `size_t` conversion in `jsi::Function::createFromHostFunction(…)`

docs/docs/view-components.md, packages/nitrogen/src/views/kotlin/KotlinHybridViewManager.ts, packages/react-native-nitro-image/android/src/main/java/com/margelo/nitro/image/HybridTestView.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/views/HybridTestViewManager.kt
Technically a breaking change, but before it was broken too because views must have a `ThemedReactContext`.
=> feat: Add `context` as a parameter to `HybridView`s

packages/template/android/src/main/java/com/margelo/nitro/$$androidNamespace$$/$$androidCxxLibName$$Package.java
Fix Android build by removing `HybridObjectRegistry` from the template, following its removal from core in #579.
=> fix: removes deprecated `HybridObjectRegistry` from template

packages/nitrogen/src/getPlatformSpecs.ts
Fix for `getHybridViewPlatforms` implementation that didn't properly handle platform specifications.
The previous implementation didn't get TypeAlias args correctly - it was always returning an empty array, 
which caused it to default to both iOS and Android platforms regardless of user specification.
Now if a user specifies the platform in the View definition like:
```ts
export type TestView = HybridView<TestViewProps, TestViewMethods, { ios: 'swift' }>
```
it correctly picks only the iOS platform.
> [!NOTE]
> I tested this with interfaces and it doesn't work as the check is explicitly for TypeAlias declarations. The previous implementation didn't work for interfaces either.
If handling interfaces is an option let me know I will open another PR to handle this change.
=> fix: correct `HybridView` platform detection for `TypeAliasDeclarations`

packages/react-native-nitro-modules/cpp/core/HybridObject.cpp
In debug, all Hybrid Objects are now frozen. This prevents the following bugs:
```
object.someValeu = 5
```
As you can see, the user (who might not be using TypeScript (stupid idea btw)) mistyped `someValue` and instead set `someValeu`. This just does _nothing_ and sets the prop on the `jsi::Object`, instead of going into the native hybrid object.
With this change, the issue is now fixed, and the object can no longer be modified (in debug) as it's now frozen.
=> feat: Freeze objects in debug

packages/react-native-nitro-modules/cpp/core/HybridObject.cpp
This PR reverts #602 as it breaks Unistyles.
Freezing objects is indeed a good approach, but it compromises Nitro's flexibility to override certain JS-only properties.  
One use case is mapping React Native `StyleSheet` properties like `compose` and `flatten` to my Hybrid.
I considered exposing some setters on my side, but that feels like overkill for such a simple case.
=> fix: revert Object.freeze

packages/nitrogen/src/syntax/Property.ts, packages/nitrogen/src/syntax/helpers.ts, packages/react-native-nitro-image/android/src/main/java/com/margelo/nitro/image/HybridTestView.kt, packages/react-native-nitro-image/ios/HybridTestView.swift, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestViewSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestViewSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/views/JHybridTestViewStateUpdater.cpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/HybridTestViewSpec.kt, packages/react-native-nitro-image/nitrogen/generated/ios/c++/HybridTestViewSpecSwift.hpp, packages/react-native-nitro-image/nitrogen/generated/ios/c++/views/HybridTestViewComponent.mm, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestViewSpec.swift, packages/react-native-nitro-image/nitrogen/generated/ios/swift/HybridTestViewSpec_cxx.swift, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestViewSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/HybridTestViewSpec.hpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/views/HybridTestViewComponent.cpp, packages/react-native-nitro-image/nitrogen/generated/shared/c++/views/HybridTestViewComponent.hpp, packages/react-native-nitro-image/nitrogen/generated/shared/json/TestViewConfig.json, packages/react-native-nitro-image/src/specs/TestView.nitro.ts
In Kotlin and Swift, a boolean property that starts with `is` will have a getter that doesn't have the `get` prefix.
```swift
class Test {
var isWith = false
var without = false
}
```
This generates those getters:
```swift
bool Test::isWith();
bool Test::getWithout();
```
This worked for boolean properties that start with `is`, but I forgot to also add this to properties that are prefixed with `has`. This PR changes this, now it also works for `hasSomething`.
- fixes #648
=> fix: Fix boolean properties with `has` prefix generating wrong names

packages/nitrogen/src/syntax/kotlin/KotlinCxxBridgedType.ts, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JHybridTestViewSpec.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/JJsStyleStruct.hpp
This commit updates the generated C++ glue code to use `jni::make_global()` to avoid invalid memory access and ensure safe interop with Java/Kotlin-managed objects.
Closes: #654
=> fix(android): prevent crash when returning callback functions by safely capturing weak JNI references

bun.lock, example/package.json, package.json, packages/react-native-nitro-image/package.json, packages/react-native-nitro-modules/package.json, packages/template/package.json
This fixes a bunch of bundle & runtime errors i was getting on android.
I also had it in other projects that were using RN 0.78.0 that I wasn't able to bundle JS. This fixes it
=> chore(example): upgrade example app to RN 0.78.2

packages/nitrogen/src/views/kotlin/KotlinHybridViewManager.ts, packages/react-native-nitro-image/nitrogen/generated/android/c++/views/JHybridTestViewStateUpdater.cpp, packages/react-native-nitro-image/nitrogen/generated/android/c++/views/JHybridTestViewStateUpdater.hpp, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/views/HybridTestViewManager.kt, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/views/HybridTestViewStateUpdater.kt, packages/react-native-nitro-modules/android/CMakeLists.txt, packages/react-native-nitro-modules/android/src/main/cpp/views/JStateWrapper.hpp
In RN 0.80 they made the `StateWrapperImpl.java` internal, which we relied on:
- https://github.com/facebook/react-native/commit/9f941c50c970e35ac6fcfa11848d1f7f5a0a9323
This solution doesn't use `StateWrapperImpl` on the java side anywhere, but just the public `StateWrapper` class (which is just an interface, but is part of the public API).
On the C++ side we then cast the `jobject` to the concrete `StateWrapperImpl` type which we know it should be.
The good thing is, is that this change is backwards compatible as well. It doesn't break anything for users that are not yet on RN 0.80.
=> fix: RN 0.80 compatibility 

packages/react-native-nitro-image/android/build.gradle, packages/react-native-nitro-modules/android/build.gradle, packages/template/android/build.gradle
Enables support for 16 KB page sizes on Android.
Each Nitro Module library will need to define this for themselves too in their `build.gradle` file.
See [Support 16 KB page sizes](https://developer.android.com/guide/practices/page-sizes) for more information.
=> feat: Enable 16 KB page size on Android

packages/nitrogen/src/views/kotlin/KotlinHybridViewManager.ts, packages/react-native-nitro-image/nitrogen/generated/android/kotlin/com/margelo/nitro/image/views/HybridTestViewManager.kt
Leaving this in might cause build error on RN 0.80, but either way we don't need this.
=> fix: remove unused StateWrapperImpl import

example/package.json
We need to keep the .xcode.env.local file for builds to work correctly.
Otherwise on a fresh setup we get errors like this during building:
=> chore(example): fix iOS building issues

packages/nitrogen/src/syntax/swift/SwiftCxxTypeHelper.ts, packages/react-native-nitro-test/nitrogen/generated/ios/NitroTest-Swift-Cxx-Bridge.hpp
Marks the Swift function wrapper type as `~Copyable` (`SWIFT_NONCOPYABLE` in C++) to avoid `std::shared_ptr` copies each time. 
Should improve performance for functions that take callbacks.
=> perf: Make Swift function wrappers faster by avoiding copies

packages/react-native-nitro-modules/NitroModules.podspec, packages/react-native-nitro-modules/nitro_pod_utils.rb
Helps with problems as reported here:
- https://github.com/facebook/react-native/issues/52366
On RN 0.80 we no longer need to specify folly flags, neither with or without using static frameworks
=> fix(ios): only apply folly compiler flags on RN < 80 (fix RN 0.80 compat)

example/src/Testers.ts, example/src/getTests.ts, packages/react-native-nitro-modules/cpp/core/HybridFunction.hpp, packages/react-native-nitro-modules/cpp/jsi/JSIConverter+Exception.hpp
This requires RN 0.80, but errors in Android are finally fully propagated to JS!
=> fix: Properly throw errors on Android now on RN 0.80

packages/nitrogen/src/utils.ts
Makes nitrogen 4x faster (shaves off 3.8 seconds on nitrogen) by using a faster path.join implementation.
```
🎉  Generated 5/5 HybridObjects in 4.0s!
```
```
🎉  Generated 5/5 HybridObjects in 1.1s!
```
=> perf: Make nitrogen 4x faster by using unsafe fast path join

packages/nitrogen/src/syntax/swift/SwiftHybridObject.ts, packages/react-native-nitro-test/nitrogen/generated/ios/swift/HybridBaseSpec.swift, packages/react-native-nitro-test/nitrogen/generated/ios/swift/HybridChildSpec.swift, packages/react-native-nitro-test/nitrogen/generated/ios/swift/HybridTestObjectSwiftKotlinSpec.swift, packages/react-native-nitro-test/nitrogen/generated/ios/swift/HybridTestViewSpec.swift
Makes a Swift HybridObject's `init` function public to allow it being overridden/implemented/called from code outside of this module.
E.g. when implementing a HybridObject's Spec from a different module, this was an error before.
=> fix: Make `init` public

packages/nitrogen/src/autolinking/ios/createSwiftCxxBridge.ts, packages/nitrogen/src/config/NitroConfig.ts, packages/nitrogen/src/syntax/swift/SwiftCxxTypeHelper.ts, packages/react-native-nitro-test/nitrogen/generated/ios/NitroTest-Swift-Cxx-Bridge.cpp
Instead of trying to convert external types on our own in the bridge, we import the external Cxx bridge and just forward to their implementation.
=> fix: Properly use external bridge implementation

packages/nitrogen/src/syntax/kotlin/KotlinCxxBridgedType.ts, packages/react-native-nitro-test/nitrogen/generated/android/c++/JHybridTestObjectSwiftKotlinSpec.cpp, packages/react-native-nitro-test/nitrogen/generated/android/kotlin/com/margelo/nitro/test/HybridTestObjectSwiftKotlinSpec.kt
Update logic for determining when a Kotlin type bridged to C++ requires special handling, specifically improving support for nested structs. The main changes clarify that structs do not need special handling and ensure that optionals defer to their wrapped type's requirements
fixes #795
=> fix: add special handling logic for structs `KotlinCxxBridgedType`

packages/nitrogen/src/getFiles.ts, packages/nitrogen/src/nitrogen.ts, packages/nitrogen/src/utils.ts, packages/react-native-nitro-test/nitrogen/generated/android/c++/JFunc_void_double.hpp, packages/react-native-nitro-test/nitrogen/generated/android/kotlin/com/margelo/nitro/test/Func_void_double.kt, packages/react-native-nitro-test/nitrogen/generated/ios/swift/Func_void_double.swift, packages/react-native-nitro-test/nitrogen/generated/ios/swift/Func_void_std__string.swift
1. I was walking the full array recursively, so it wasn't O(n) to dedupe files but rather O(n^2)!! 
2. I was comparing the `file.content`, which is an expensive string comparison (character by character) each time. Also called O(n^2) lol
3. Instead of recursive loops, I use a hash map to efficiently store files via their full paths. Makes things O(n) and fast.
=> perf: Speed up Nitrogen by 94x by making `filterDuplicateFiles(…)` O(n) instead of O(n²) 🤯

packages/nitrogen/src/syntax/kotlin/KotlinStruct.ts, packages/react-native-nitro-test/nitrogen/generated/android/kotlin/com/margelo/nitro/test/Car.kt, packages/react-native-nitro-test/nitrogen/generated/android/kotlin/com/margelo/nitro/test/JsStyleStruct.kt, packages/react-native-nitro-test/nitrogen/generated/android/kotlin/com/margelo/nitro/test/MapWrapper.kt, packages/react-native-nitro-test/nitrogen/generated/android/kotlin/com/margelo/nitro/test/Person.kt, packages/react-native-nitro-test/nitrogen/generated/android/kotlin/com/margelo/nitro/test/WrappedJsStruct.kt
Kotlin structs were holding the Kotlin-friendly types (e.g. `() -> Unit`) instead of the Cxx-ready types (e.g. `Func_void`).
This caused errors when converting Kotlin structs to C++ as C++ couldn't find the Cxx-ready types in the `data class`.
Now this is fixed and the Kotlin structs actually hold the Cxx-ready type, and provides a convenience initializer for Kotlin.
=> fix: Fix Kotlin structs not holding the Cxx types

example/src/getTests.ts, packages/react-native-nitro-modules/cpp/entrypoint/HybridNitroModulesProxy.cpp, packages/react-native-nitro-modules/cpp/entrypoint/HybridNitroModulesProxy.hpp, packages/react-native-nitro-modules/src/NitroModulesProxy.ts
Adds a method to check whether the given object is a `HybridObject` or not.
=> feat: Add `NitroModules.isHybridObject(...)`

packages/nitrogen/src/syntax/swift/SwiftCxxTypeHelper.ts, packages/react-native-nitro-test-external/nitrogen/generated/ios/NitroTestExternal-Swift-Cxx-Bridge.cpp, packages/react-native-nitro-test-external/nitrogen/generated/ios/NitroTestExternal-Swift-Cxx-Bridge.hpp, packages/react-native-nitro-test/nitrogen/generated/ios/NitroTest-Swift-Cxx-Bridge.cpp, packages/react-native-nitro-test/nitrogen/generated/ios/NitroTest-Swift-Cxx-Bridge.hpp
Swift cannot catch C++ exceptions anyways.
=> perf: Make all C++ bridge functions `noexcept`

packages/react-native-nitro-modules/cpp/core/HybridObject.hpp
=> fix: Throw better error message in default `HybridObject` constructor

packages/react-native-nitro-modules/NitroModules.podspec
Fixes https://github.com/mrousavy/react-native-nitro-image/issues/52
=> fix: Fix build on RN 0.79 or lower
